branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Enable building pull requests.
    - master

language: rust
sudo: false
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"
cache: cargo

rust:
os:
  - linux
  - windows
  - osx

matrix:
  include:
  # This build uses stable and checks rustfmt and clippy.
  # We don't check them on nightly since their lints and formatting may differ.
  - rust: stable
    install:
      - rustup component add rustfmt-preview
      - rustup component add clippy-preview
    before_script:
      - cargo fmt --all -- --check
      - cargo clippy --all -- -D clippy
  # Since many users will use nightlies, also test that.
  - rust: nightly


script:
  - docker run --name pd -p 2379:2379 --rm pingcap/pd --name "pd" --data-dir "pd" --client-urls "http://127.0.0.1:2379" --advertise-client-urls "http://127.0.0.1:2379"
  - docker run --name kv -p 2380:2380 --rm pingcap/tikv --pd-endpoints "127.0.0.1:2379" -addr "127.0.0.1:2380" --data-dir "kv"
  - cargo test --all -- --nocapture
  # Validate benches still work.
  - cargo bench --all -- --test
